server:
  # 服务端口
  port: 9999

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.65:33063/uppv2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Conlin2020

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.conlin.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-fetch-size: 512
